### PR TITLE
Update documentation with BM25+ weighting function.

### PR DESCRIPTION
**Pull request by ivmarkp**
I have added BM25+ weighting function details in relevant places (howtos and glossary) I could figure. Please let me know if I need to be more comprehensive with the details and about other places that I might have missed.

### CODE REVIEW

**Comment by jaylett** [comment]
It's a little difficult always to anticipate what people reading the documentation want to know, but I think we probably want to focus first on how BM25+ might be better than BM25, and later on how it was developed (including the paper reference). So perhaps adding a bit at the beginning about situations where BM25+ might be helpful, probably based on this sentence:

> As a result, the occurrences of a query term in very long documents may not
> be rewarded properly by BM25, and thus those very long documents could be overly
> penalized.

I'm not sure we need BM25 in the glossary, but again if it should be there it should focus on how it's useful to users rather than its development (which in any case is skewed in this text towards BM25+).

**Comment by ivmarkp** [comment]
This is my first experience writing a documentation for something that would be read by real users to be honest :) I'll just follow your suggestions carefully. 

>   I'm not sure we need BM25 in the glossary, but again if it should be there it should focus on how it's useful to users rather than its development (which in any case is skewed in this text towards BM25+).

I can't decide whether to include BM25+ in the glossary or not.  But looking the weighting schemes that we currently have in glossary i.e BM25, Dfr and LM, I think we should consider including more weighting schemes in the glossary.

**Comment by jaylett** [comment]
I think the right thing to do is to have things in the glossary that crop up a lot and people might be confused by otherwise. Maybe for BM25+ we should extend the BM25 entry with a paragraph based on what you've already written? It'll be in the same place in the glossary, so it's still findable.

**Comment by ojwb** [comment]
I think that most people reading documentation about BM25 and BM25+ probably primarily want guidance on which they should use (and what sort of situations each is typically better in if it's not the case that one is always better and then other really only interesting for things like a baseline in academic evaluations).

Providing a link to the academic literature for those wanting to see the theoretical background would be useful too I think.

**Comment by ivmarkp** [comment]
Closing this PR and opening a new one to have all documentation changes in a single PR.

**Pull request closed without merging**
